### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by notpushkin** [trckster/termorize#7]
Hey, first of all thanks for your wonderful project!

I've noticed this repo lacks a LICENSE file, which is the usual way of specifying the project's license. This means the project is [not licensed / non-open source](https://choosealicense.com/no-permission/), and people can't use it legally. Could you [pick a license](https://choosealicense.com/) and add it to the repo? Let me know if you need any help with that!

**Comment by trckster** [comment]
Hello, thank you for your kind words and for bringing up the issue of the missing LICENSE file. We appreciate your concern about the legal status of the project.

As for the license, we understand the importance of specifying one and we will work on it. We apologize for any inconvenience this might have caused.

If you are willing to help us with this matter, we would be grateful. Please feel free to create a pull request with the license of your choice and we will review it as soon as possible.

Thank you for your support and for bringing this to our attention.

**Comment by notpushkin** [comment]
Certainly! I'm glad that you are taking this matter seriously and are willing to work on specifying a license for your project.

Here are a few things to consider when choosing a license for your project:

- **Attribution:** Some licenses require that you give credit to the original authors of the code, which can be important if you are using code from other sources.
- **Redistribution:** Some licenses have more restrictive requirements for redistributing the code, so it's important to choose a license that allows you to share the code with others as you see fit.
- **Compatibility:** Some licenses are incompatible with each other, so it's important to choose a license that is compatible with the other open source software that you are using in your project.

Based on the size of the project, I suggest sticking with time-proven choice of [AGPLv3](https://choosealicense.com/licenses/agpl-3.0/). I've submitted a PR, let's discuss this further there.
